# Generated by Django 5.2.6 on 2025-09-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kinesiologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firebase_ide', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nro_titulo', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('doc_verificacion', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('completada', 'completada'), ('cancelada', 'cancelada')], default='pendiente', max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='core.kinesiologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('sentimiento', models.CharField(blank=True, choices=[('positiva', 'positiva'), ('neutral', 'neutral'), ('negativa', 'negativa')], max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseña', to='core.cita')),
            ],
        ),
    ]
