# Generated by Django 5.2.6 on 2025-10-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
