# Generated by Django 5.2.6 on 2025-10-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_paciente_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('disponible', 'disponible'), ('reservado', 'reservado'), ('no_disponible', 'no_disponible'), ('expirado', 'expirado')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupo_agenda', to='core.cita')),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='core.kinesiologo')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupo_reservado', to='core.paciente')),
            ],
        ),
    ]
