# Generated by Django 5.2.6 on 2025-10-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='metodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='pagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('pagado', 'pagado'), ('fallido', 'fallido'), ('expirado', 'expirado')], default='pendiente', max_length=20)),
                ('transa_id_externo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscripcion', to='core.kinesiologo')),
                ('metodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='core.metodopago')),
            ],
        ),
    ]
