# Generated by Django 5.2.6 on 2025-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_metodopago_pagosuscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosuscripcion',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pagosuscripcion',
            name='orden_comercio',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pagosuscripcion',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagosuscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('pagado', 'pagado'), ('fallido', 'fallido'), ('expirado', 'expirado')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
