# Generated by Django 5.2.6 on 2025-11-10 23:19

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pagosuscripcion_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinesiologo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.kx_profile_upload_path),
        ),
        migrations.CreateModel(
            name='documentoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ID_FRENTE', 'Carnet frente'), ('ID_REVERSO', 'Carnet reverso'), ('TITULO', 'Título/diploma'), ('CERTIFICADO', 'Certificado adicional'), ('OTRO', 'Otro')], max_length=20)),
                ('archivo', models.FileField(upload_to=core.models.kx_doc_upload_path)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado')], default='pendiente', max_length=10)),
                ('comentario_revisor', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.kinesiologo')),
            ],
        ),
    ]
