# Generated by Django 5.2.6 on 2025-11-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kinesiologo_foto_perfil_documentoverificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('pagado', 'pagado'), ('fallido', 'fallido')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='pagoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('pagado', 'pagado'), ('fallido', 'fallido')], db_index=True, default='pendiente', max_length=20)),
                ('buy_order', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=120, null=True)),
                ('token_ws', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_cita', to='core.cita')),
                ('kinesiologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_citas', to='core.kinesiologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_citas', to='core.paciente')),
            ],
        ),
    ]
